### ISSUE TITLE
non-validator-docs no peers

### ISSUE THREAD

**Issue by lk479o000** [AME-AMEChain/amechain_quantum#3]
https://amechain.io/non-validator-docs/

I deployed with reference to the document, but couldn't synchronize the main network node
No reply to the amechain email. 
Somebody asked me to check amechain.io in the telegram.
how can i do?

cat /root/amechain_quantum/amechain/config/permissions_config.toml
# accounts-allowlist=["*"]

nodes-allowlist=[
    # node1.amechain.io
    "enode://14b274edb0df84844593ab6bf0f26881ffc4c305fe58242fa1a2ff79d761441db3548044f27f7a84b3aabd509edf1cace1b94608b42ebfde5a022e5c2ff50d8d@167.71.230.219:30303",

    # node2.amechain.io
    "enode://aeebb5702dbe25441a21065f66a979c04faa5dd3a091c2e6454567c1d5ec1464dc420a5d5ca6cec5e5bba317da28bc8806795451be0b00eb2df16fb1e4ce0507@142.93.50.13:30303",

    # node3.amechain.io
    "enode://106e831aee108a5aaab6daf1cc5d1deb212b808a7bd5b818a0f4731e04986a85319a7058cf7fc5bc2f5099820e826d4138c3a04651f0062509e548b08ba1889e@167.172.47.87:30303",

    # node4.amechain.io
    "enode://a2868cd0295a04f5e9e1cdec7544521eeb212d7542adf7ba74e16aefbea45662a9c8d8486346beb97f530fe76ecbe79a34cb85d52e2dc18f0922ac3002df40a3@167.71.201.159:30303"

]

journalctl -u amechain_node -f
Mar 09 07:47:08 f33620361fab amechain-node[6126]: 2023-03-09 07:47:08.632+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers. Current peers: 0
Mar 09 07:47:13 f33620361fab amechain-node[6126]: 2023-03-09 07:47:13.633+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers. Current peers: 0
Mar 09 07:47:18 f33620361fab amechain-node[6126]: 2023-03-09 07:47:18.633+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers. Current peers: 0
Mar 09 07:47:23 f33620361fab amechain-node[6126]: 2023-03-09 07:47:23.634+00:00 | EthScheduler-Timer-0 | INFO  | FullSyncTargetManager | No sync target, waiting for peers. Current peers: 0

**Comment by Itsdamntrue** [comment]
Where did you get my mail !?
